#pragma once

#include "core/executionreport.h"
#include <QVector>
#include <QWidget>
#include <atomic>

class QGroupBox;
class QLineEdit;
class QPlainTextEdit;
class QProgressBar;
class QPushButton;
class QLabel;
class QTableWidget;
class QThread;

Q_DECLARE_METATYPE(ExecutionReport)
Q_DECLARE_METATYPE(QVector<ExecutionReport>)

class EngineWorker : public QObject {
    Q_OBJECT

  public:
    explicit EngineWorker(QString inputFilePath, QString outputFilePath, QObject *parent = nullptr);

  public slots:
    void run();
    void requestCancel();

  signals:
    void progress(int percent);
    void logLine(QString line);
    void finished(QVector<ExecutionReport> reports);
    void error(QString message);

  private:
    bool isCancelled() const;
    static QString timestamped(const QString &message);

    QString inputFilePath_;
    QString outputFilePath_;
    std::atomic_bool cancelRequested_{false};
};

class ImportExportPanel : public QWidget {
    Q_OBJECT

  public:
    explicit ImportExportPanel(QWidget *parent = nullptr);
    ~ImportExportPanel() override;

  signals:
    void resultsReady(QVector<ExecutionReport> reports);

  private slots:
    void onBrowseInputClicked();
    void onBrowseOutputClicked();
    void onRunButtonClicked();
    void onClearLogClicked();
    void onWorkerProgress(int percent);
    void onWorkerLogLine(const QString &line);
    void onWorkerFinished(QVector<ExecutionReport> reports);
    void onWorkerError(QString message);
    void onWorkerThreadFinished();

  private:
    void setupUi();
    QGroupBox *buildInputGroup();
    QGroupBox *buildOutputGroup();
    QGroupBox *buildRunGroup();
    void loadInputPreview(const QString &filePath);
    void appendLogLine(const QString &line);
    void setRunningState(bool running);
    void startWorker();
    QString ensureOutputPath();

    static QString autoOutputPathForInput(const QString &inputFilePath);
    static QString timestamped(const QString &message);
    static QStringList splitCommaSeparated(const QString &line);
    static bool isHeaderRow(const QStringList &tokens);

    QLineEdit *inputPathEdit_{nullptr};
    QPushButton *inputBrowseButton_{nullptr};
    QTableWidget *previewTable_{nullptr};
    QLabel *rowCountLabel_{nullptr};

    QLineEdit *outputPathEdit_{nullptr};
    QPushButton *outputBrowseButton_{nullptr};
    QString autoGeneratedOutputPath_;

    QProgressBar *progressBar_{nullptr};
    QPushButton *runButton_{nullptr};
    QPlainTextEdit *logView_{nullptr};
    QPushButton *clearLogButton_{nullptr};

    QThread *workerThread_{nullptr};
    EngineWorker *worker_{nullptr};
    bool runInProgress_{false};
};
